name: CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: johannaizu/univent
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      

  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploying to kubernetes
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            kubectl rollout restart deployment univent-deployment
